packages:
  - .
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  embedded-postgres: true
  '@embedded-postgres/windows-x64': true
  '@embedded-postgres/linux-x64': true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1145.0'
  - '@aws-sdk/s3-request-presigner@3.1145.0'
